### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by pmatyja** [timjroberts/typescript-atomizer-deploy#7]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Pro
**Thrown From**: [typescript-atomizer](https://github.com/timjroberts/typescript-atomizer-deploy) package, v0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:9379

TypeError: Cannot read property 'version' of undefined
  at HostCache.getVersion (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\TypeScript\typescriptServices.js:32891:43)
  at sourceFileUpToDate (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\TypeScript\typescriptServices.js:33246:67)
  at programUpToDate (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\TypeScript\typescriptServices.js:33257:22)
  at synchronizeHostData (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\TypeScript\typescriptServices.js:33265:17)
  at Object.getSyntacticDiagnostics (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\TypeScript\typescriptServices.js:33324:13)
  at TypeScriptTextEditor.getLanguageDiagnostics (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\TypeScriptTextEditor.js:180:49)
  at TypeScriptTextEditorState.updateDiagnosticMarkers (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\state\TypeScriptTextEditorState.js:359:56)
  at TypeScriptTextEditorState.updateFromContentChange (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\state\TypeScriptTextEditorState.js:346:18)
  at TypeScriptWorkspace.onTypeScriptTextEditorContentsChanged (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\TypeScriptWorkspace.js:102:15)
  at AnonymousObserver._onNext (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\TypeScriptWorkspace.js:62:135)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:1950:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:1882:35)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:9516:19)
  at AnonymousObserver._onNext (C:\Users\Yankee\.atom\packages\typescript-atomizer\lib\TypeScriptTextEditor.js:44:38)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:1950:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:1882:35)
  at AutoDetachObserverPrototype.next (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:9376:23)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:1882:35)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:9516:19)
  at AutoDetachObserverPrototype.next (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:9376:23)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:1882:35)
  at AutoDetachObserverPrototype.next (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:9376:23)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:1882:35)
  at innerHandler (C:\Users\Yankee\.atom\packages\typescript-atomizer\node_modules\rx\dist\rx.all.js:5615:18)
  at Emitter.module.exports.Emitter.emit (C:\Users\Yankee\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Yankee\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1263:25

```

### Commands

```
     -3:32.5.0 core:save (atom-text-editor.editor.is-focused)
     -3:32.5.0 linter:lint (atom-text-editor.editor.is-focused)
     -2:23 typescript:build (atom-text-editor.editor.is-focused)
     -2:19.4.0 linter:lint (atom-text-editor.editor.is-focused)
     -2:15 core:cut (atom-text-editor.editor.is-focused)
     -2:14.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:14.8.0 linter:lint (atom-text-editor.editor.is-focused)
     -2:13.5.0 typescript:build (atom-text-editor.editor.is-focused)
  7x -1:56.9.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:17.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:16.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.9.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.8.0 linter:lint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "E:\\Programowanie",
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-html-preview, v0.1.11
atom-typescript, v6.0.2
linter, v1.5.0
minimap, v4.13.2
monokai, v0.18.0
typescript-atomizer, v0.3.1

# Dev
No dev packages
```

**Comment by timjroberts** [comment]
Hi @pmatyja - I'm no longer maintaining this project. If you want excellent TypeScript support in Atom then please consider https://github.com/TypeStrong/atom-typescript
